# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    #esi: true
    #fragments: true
    php_errors:
        log: true

    validation: { enabled: true }
    serializer:
        circular_reference_handler: App\Service\CircularReferenceHandler

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
